### ISSUE TITLE
Synchronize all the data format to the updated version

### ISSUE THREAD

**Issue by wdan** [HKUST-VISLab/vismooc-data-server#39]

**Comment by wdan** [comment]
Also explicitly describe the fields of metaInfo.

**Comment by wdan** [comment]
Mark all the statistical (2-level) features

**Comment by chenzhutian** [comment]
finish

**Comment by wdan** [comment]
Two issues:

1. The name of ‘metaInfo' should not be 'metalInfo'
2. The example metaInfo format for table 'courses' and 'videos'
@chenzhutian
