### ISSUE TITLE
fix the inconsistent schema in data processor

### ISSUE THREAD

**Issue by chenzhutian** [HKUST-VISLab/vismooc-data-server#40]
sync follows the schema

**Comment by chenzhutian** [comment]
I think I have fixed this problem.
please merge the code from branch dev to your branch, then test the code.
@shaozu

**Comment by wdan** [comment]
Also remember to check the number of users problem for user table

**Comment by chenzhutian** [comment]
other metaInfo need to be discussed in the future.
Currently, this issue has been addressed. Data followed the right schema could be fetched from db now.
